import type { Rows } from "@/modules/reports/renderers/minor-behavior-log/sections";

export const MOCK_DATE_FROM = new Date("2026-03-01");
export const MOCK_DATE_TO = new Date("2026-03-14");

const student = (id: string, firstName: string, lastName: string) => ({
  id,
  studentId: `STU-${id}`,
  firstName,
  middleName: null,
  lastName,
  dateOfBirth: new Date("2013-01-01"),
  gender: null,
  status: "ACTIVE" as const,
  photoUrl: null,
  notes: null,
  deletedAt: null,
  deletedBy: null,
  createdAt: new Date("2024-08-01"),
  updatedAt: new Date("2024-08-01"),
});

const behaviorCategory = (id: string, code: string, name: string) => ({
  id,
  code,
  name,
  type: "NEGATIVE" as const,
  isActive: true,
});

const actionCode = (id: string, code: string, name: string) => ({
  id,
  code,
  name,
  isActive: true,
  sortOrder: 0,
});

const categorySelection = (recordId: string, cat: ReturnType<typeof behaviorCategory>) => ({
  id: `${recordId}-cat-${cat.id}`,
  behaviorRecordId: recordId,
  behaviorCategoryId: cat.id,
  createdAt: new Date("2024-08-01"),
  behaviorCategory: cat,
});

const actionSelection = (recordId: string, code: ReturnType<typeof actionCode>) => ({
  id: `${recordId}-act-${code.id}`,
  behaviorRecordId: recordId,
  actionCodeId: code.id,
  createdAt: new Date("2024-08-01"),
  actionCode: code,
});

const recordedBy = {
  id: "mock-user-teacher",
  roleId: "mock-role-teacher",
  email: "m.alvarez@example.edu",
  passwordHash: "",
  fullName: "Ms. Alvarez",
  isActive: true,
  lastLoginAt: null,
  deletedAt: null,
  deletedBy: null,
  createdAt: new Date("2024-08-01"),
  updatedAt: new Date("2024-08-01"),
};

export const MOCK_MINOR_BEHAVIOR_ROWS: Rows = [
  {
    record: {
      id: "mock-record-1",
      studentId: "mock-student-1",
      incidentId: null,
      counselingSessionId: null,
      recordedByUserId: "mock-user-teacher",
      recordDate: new Date("2026-03-02"),
      recordTime: "09:15",
      description: "Talking during silent reading time.",
      otherBehaviorText: null,
      otherActionText: null,
      classroomReference: "Room 12",
      academicYearId: "mock-academic-year",
      reportingPeriodId: null,
      deletedAt: null,
      deletedBy: null,
      createdAt: new Date("2026-03-02T09:20:00"),
      updatedAt: new Date("2026-03-02T09:20:00"),
      student: student("mock-student-1", "Amara", "Chen"),
      categories: [categorySelection("mock-record-1", behaviorCategory("mock-cat-d", "D", "Disruption/Noise"))],
      actions: [actionSelection("mock-record-1", actionCode("mock-action-w", "W", "Verbal Warning"))],
      recordedBy,
    },
    isChronic: false,
    chronicCount: 1,
  },
  {
    record: {
      id: "mock-record-2",
      studentId: "mock-student-2",
      incidentId: null,
      counselingSessionId: null,
      recordedByUserId: "mock-user-teacher",
      recordDate: new Date("2026-03-03"),
      recordTime: "11:00",
      description: "Refused to put phone away after two reminders.",
      otherBehaviorText: null,
      otherActionText: null,
      classroomReference: "Room 12",
      academicYearId: "mock-academic-year",
      reportingPeriodId: null,
      deletedAt: null,
      deletedBy: null,
      createdAt: new Date("2026-03-03T11:05:00"),
      updatedAt: new Date("2026-03-03T11:05:00"),
      student: student("mock-student-2", "Diego", "Ramirez"),
      categories: [categorySelection("mock-record-2", behaviorCategory("mock-cat-n", "N", "Non-Compliance"))],
      actions: [actionSelection("mock-record-2", actionCode("mock-action-s", "S", "Seat Change"))],
      recordedBy,
    },
    isChronic: false,
    chronicCount: 1,
  },
  {
    record: {
      id: "mock-record-3",
      studentId: "mock-student-3",
      incidentId: null,
      counselingSessionId: null,
      recordedByUserId: "mock-user-teacher",
      recordDate: new Date("2026-03-04"),
      recordTime: "08:50",
      description: "Making noise while others were presenting.",
      otherBehaviorText: null,
      otherActionText: null,
      classroomReference: "Room 9",
      academicYearId: "mock-academic-year",
      reportingPeriodId: null,
      deletedAt: null,
      deletedBy: null,
      createdAt: new Date("2026-03-04T08:55:00"),
      updatedAt: new Date("2026-03-04T08:55:00"),
      student: student("mock-student-3", "Priya", "Nair"),
      categories: [categorySelection("mock-record-3", behaviorCategory("mock-cat-d", "D", "Disruption/Noise"))],
      actions: [actionSelection("mock-record-3", actionCode("mock-action-w", "W", "Verbal Warning"))],
      recordedBy,
    },
    isChronic: false,
    chronicCount: 1,
  },
  {
    record: {
      id: "mock-record-4",
      studentId: "mock-student-3",
      incidentId: null,
      counselingSessionId: null,
      recordedByUserId: "mock-user-teacher",
      recordDate: new Date("2026-03-07"),
      recordTime: "13:20",
      description: "Interrupting the teacher repeatedly.",
      otherBehaviorText: null,
      otherActionText: null,
      classroomReference: "Room 9",
      academicYearId: "mock-academic-year",
      reportingPeriodId: null,
      deletedAt: null,
      deletedBy: null,
      createdAt: new Date("2026-03-07T13:25:00"),
      updatedAt: new Date("2026-03-07T13:25:00"),
      student: student("mock-student-3", "Priya", "Nair"),
      categories: [categorySelection("mock-record-4", behaviorCategory("mock-cat-d", "D", "Disruption/Noise"))],
      actions: [actionSelection("mock-record-4", actionCode("mock-action-c", "C", "Cooling-off Break"))],
      recordedBy,
    },
    isChronic: false,
    chronicCount: 2,
  },
  {
    record: {
      id: "mock-record-5",
      studentId: "mock-student-3",
      incidentId: null,
      counselingSessionId: null,
      recordedByUserId: "mock-user-teacher",
      recordDate: new Date("2026-03-10"),
      recordTime: "10:05",
      description: "Third disruption this cycle — recommend Tier 2 support.",
      otherBehaviorText: null,
      otherActionText: null,
      classroomReference: "Room 9",
      academicYearId: "mock-academic-year",
      reportingPeriodId: null,
      deletedAt: null,
      deletedBy: null,
      createdAt: new Date("2026-03-10T10:10:00"),
      updatedAt: new Date("2026-03-10T10:10:00"),
      student: student("mock-student-3", "Priya", "Nair"),
      categories: [categorySelection("mock-record-5", behaviorCategory("mock-cat-d", "D", "Disruption/Noise"))],
      actions: [actionSelection("mock-record-5", actionCode("mock-action-e", "E", "Escalated (3+)"))],
      recordedBy,
    },
    isChronic: true,
    chronicCount: 3,
  },
  {
    record: {
      id: "mock-record-6",
      studentId: "mock-student-4",
      incidentId: null,
      counselingSessionId: null,
      recordedByUserId: "mock-user-teacher",
      recordDate: new Date("2026-03-11"),
      recordTime: null,
      description: null,
      otherBehaviorText: null,
      otherActionText: null,
      classroomReference: "Gym",
      academicYearId: "mock-academic-year",
      reportingPeriodId: null,
      deletedAt: null,
      deletedBy: null,
      createdAt: new Date("2026-03-11T14:00:00"),
      updatedAt: new Date("2026-03-11T14:00:00"),
      student: student("mock-student-4", "Noah", "Kim"),
      categories: [categorySelection("mock-record-6", behaviorCategory("mock-cat-p", "P", "Rough Play"))],
      actions: [],
      recordedBy,
    },
    isChronic: false,
    chronicCount: 1,
  },
];
