import { MOCK_COUNSELING_SESSION } from "@/modules/reports/renderers/counseling-case-report/mock-data";
import { MOCK_MAJOR_INCIDENT } from "@/modules/reports/renderers/major-incident-report/mock-data";
import { MOCK_MINOR_BEHAVIOR_ROWS } from "@/modules/reports/renderers/minor-behavior-log/mock-data";
import type { StudentFullReportData } from "@/modules/reports/renderers/student-full-report/sections";

export const MOCK_STUDENT_FULL_REPORT: StudentFullReportData = {
  student: {
    id: "mock-student-1",
    studentId: "STU-mock-student-1",
    firstName: "Oliver",
    middleName: null,
    lastName: "Manongko",
    dateOfBirth: new Date("2013-01-01"),
    gender: "Male",
    status: "ACTIVE",
    photoUrl: null,
    notes: null,
    deletedAt: null,
    deletedBy: null,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-01"),
    enrollments: [
      {
        id: "mock-enrollment-1",
        studentId: "mock-student-1",
        academicYearId: "mock-academic-year",
        classId: "mock-class-1",
        gradeId: "mock-grade-1",
        startDate: new Date("2024-08-01"),
        endDate: null,
        status: "ACTIVE",
        createdAt: new Date("2024-08-01"),
        updatedAt: new Date("2024-08-01"),
        grade: { id: "mock-grade-1", name: "Grade 5", level: 5, createdAt: new Date("2024-08-01") },
        class: {
          id: "mock-class-1",
          name: "Grade 5 - Rose",
          academicYearId: "mock-academic-year",
          gradeId: "mock-grade-1",
          homeroomTeacher: "Ms. Alvarez",
          createdAt: new Date("2024-08-01"),
          updatedAt: new Date("2024-08-01"),
        },
      },
    ],
    guardians: [
      {
        id: "mock-sg-1",
        studentId: "mock-student-1",
        guardianId: "mock-guardian-1",
        isPrimaryContact: true,
        isEmergencyContact: true,
        createdAt: new Date("2024-08-01"),
        guardian: {
          id: "mock-guardian-1",
          fullName: "Maria Manongko",
          relationship: "Mother",
          phone: "+62 812-3456-7890",
          email: "maria.manongko@example.com",
          address: null,
          occupation: null,
          deletedAt: null,
          deletedBy: null,
          createdAt: new Date("2024-08-01"),
          updatedAt: new Date("2024-08-01"),
        },
      },
      {
        id: "mock-sg-2",
        studentId: "mock-student-1",
        guardianId: "mock-guardian-2",
        isPrimaryContact: false,
        isEmergencyContact: true,
        createdAt: new Date("2024-08-01"),
        guardian: {
          id: "mock-guardian-2",
          fullName: "Daniel Manongko",
          relationship: "Father",
          phone: "+62 813-9876-5432",
          email: null,
          address: null,
          occupation: null,
          deletedAt: null,
          deletedBy: null,
          createdAt: new Date("2024-08-01"),
          updatedAt: new Date("2024-08-01"),
        },
      },
    ],
  },
  counselingSessions: [MOCK_COUNSELING_SESSION],
  incidents: [MOCK_MAJOR_INCIDENT],
  behaviorRows: MOCK_MINOR_BEHAVIOR_ROWS,
};
