import type { IncidentData } from "@/modules/reports/renderers/major-incident-report/sections";

export const MOCK_MAJOR_INCIDENT: IncidentData = {
  id: "mock-incident-1",
  incidentNumber: "MAJOR-2026-0042",
  primaryStudentId: "mock-student-primary",
  reportedByUserId: "mock-user-reporter",
  incidentCategoryId: "mock-category-physical",
  academicYearId: "mock-academic-year",
  severity: "MAJOR",
  incidentDate: new Date("2026-03-12"),
  incidentTime: "10:35",
  location: "East Wing Courtyard",
  status: "UNDER_INVESTIGATION",
  immediateAction: null,
  parentContactRequired: true,
  leadershipNotified: true,
  counselorOrAdminCalledAt: new Date("2026-03-12T10:42:00"),
  supportPlan:
    "Daily check-in with counselor for two weeks; seating change in homeroom.",
  deletedAt: null,
  deletedBy: null,
  createdAt: new Date("2026-03-12T11:00:00"),
  updatedAt: new Date("2026-03-12T11:00:00"),

  primaryStudent: {
    id: "mock-student-primary",
    studentId: "STU-1042",
    firstName: "Amara",
    middleName: null,
    lastName: "Chen",
    dateOfBirth: new Date("2013-05-02"),
    gender: "Female",
    status: "ACTIVE",
    photoUrl: null,
    notes: null,
    deletedAt: null,
    deletedBy: null,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-01"),
  },

  reportedBy: {
    id: "mock-user-reporter",
    roleId: "mock-role-teacher",
    email: "j.oduya@example.edu",
    passwordHash: "",
    fullName: "James Oduya",
    isActive: true,
    lastLoginAt: null,
    deletedAt: null,
    deletedBy: null,
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-01"),
  },

  incidentCategory: {
    id: "mock-category-physical",
    code: "PHYS",
    name: "Physical Aggression / Fighting",
    isActive: true,
    sortOrder: 1,
  },

  narrative: {
    id: "mock-narrative-1",
    incidentId: "mock-incident-1",
    antecedent:
      "Amara and another student were in line for the courtyard when a disagreement over a dropped basketball escalated quickly.",
    behavior:
      "Amara pushed the other student twice and raised her voice; the other student shoved back before a staff member separated them.",
    impact:
      "No injuries reported. Both students were visibly upset and the line for the next class was delayed by roughly five minutes.",
    additionalInformation:
      "Both students have a prior minor disagreement logged earlier in the term.",
    createdAt: new Date("2026-03-12T11:00:00"),
    updatedAt: new Date("2026-03-12T11:00:00"),
  },

  response: {
    id: "mock-response-1",
    incidentId: "mock-incident-1",
    studentEscortedToOffice: true,
    classroomEvacuated: false,
    firstAidOrNurseRequested: false,
    onsiteDeescalationByCounselor: true,
    additionalAction:
      "Both students given water and a few minutes to cool down before being interviewed separately.",
    createdAt: new Date("2026-03-12T11:00:00"),
    updatedAt: new Date("2026-03-12T11:00:00"),
  },

  participants: [
    {
      id: "mock-participant-1",
      incidentId: "mock-incident-1",
      studentId: "mock-student-primary",
      involvementType: "PRIMARY",
      notes: "Initiated the physical contact.",
      createdAt: new Date("2026-03-12T11:00:00"),
      student: {
        id: "mock-student-primary",
        studentId: "STU-1042",
        firstName: "Amara",
        middleName: null,
        lastName: "Chen",
        dateOfBirth: new Date("2013-05-02"),
        gender: "Female",
        status: "ACTIVE",
        photoUrl: null,
        notes: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date("2024-08-01"),
        updatedAt: new Date("2024-08-01"),
        enrollments: [
          {
            id: "mock-enrollment-1",
            studentId: "mock-student-primary",
            academicYearId: "mock-academic-year",
            classId: "mock-class-8b",
            gradeId: "mock-grade-8",
            startDate: new Date("2024-08-01"),
            endDate: null,
            status: "ACTIVE",
            createdAt: new Date("2024-08-01"),
            updatedAt: new Date("2024-08-01"),
            grade: {
              id: "mock-grade-8",
              name: "Grade 8",
              level: 8,
              createdAt: new Date("2024-08-01"),
            },
            class: {
              id: "mock-class-8b",
              name: "8B",
              academicYearId: "mock-academic-year",
              gradeId: "mock-grade-8",
              homeroomTeacher: "Ms. Alvarez",
              createdAt: new Date("2024-08-01"),
              updatedAt: new Date("2024-08-01"),
            },
          },
        ],
      },
    },
    {
      id: "mock-participant-2",
      incidentId: "mock-incident-1",
      studentId: "mock-student-second",
      involvementType: "INVOLVED",
      notes: "Shoved back once before separation.",
      createdAt: new Date("2026-03-12T11:00:00"),
      student: {
        id: "mock-student-second",
        studentId: "STU-1103",
        firstName: "Diego",
        middleName: null,
        lastName: "Ramirez",
        dateOfBirth: new Date("2013-09-18"),
        gender: "Male",
        status: "ACTIVE",
        photoUrl: null,
        notes: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date("2024-08-01"),
        updatedAt: new Date("2024-08-01"),
        enrollments: [
          {
            id: "mock-enrollment-2",
            studentId: "mock-student-second",
            academicYearId: "mock-academic-year",
            classId: "mock-class-8b",
            gradeId: "mock-grade-8",
            startDate: new Date("2024-08-01"),
            endDate: null,
            status: "ACTIVE",
            createdAt: new Date("2024-08-01"),
            updatedAt: new Date("2024-08-01"),
            grade: {
              id: "mock-grade-8",
              name: "Grade 8",
              level: 8,
              createdAt: new Date("2024-08-01"),
            },
            class: {
              id: "mock-class-8b",
              name: "8B",
              academicYearId: "mock-academic-year",
              gradeId: "mock-grade-8",
              homeroomTeacher: "Ms. Alvarez",
              createdAt: new Date("2024-08-01"),
              updatedAt: new Date("2024-08-01"),
            },
          },
        ],
      },
    },
  ],

  witnesses: [
    {
      id: "mock-witness-1",
      incidentId: "mock-incident-1",
      name: "Priya Nair",
      role: "Classmate",
      notes: "Was standing next to the line when it started.",
      createdAt: new Date("2026-03-12T11:00:00"),
    },
  ],

  categorySelections: [
    {
      id: "mock-selection-1",
      incidentId: "mock-incident-1",
      incidentCategoryId: "mock-category-physical",
      createdAt: new Date("2026-03-12T11:00:00"),
      incidentCategory: {
        id: "mock-category-physical",
        code: "PHYS",
        name: "Physical Aggression / Fighting",
        isActive: true,
        sortOrder: 1,
      },
    },
    {
      id: "mock-selection-2",
      incidentId: "mock-incident-1",
      incidentCategoryId: "mock-category-chronic",
      createdAt: new Date("2026-03-12T11:00:00"),
      incidentCategory: {
        id: "mock-category-chronic",
        code: "CHRONIC",
        name: "Chronic Minor (3+ uncorrected offenses)",
        isActive: true,
        sortOrder: 6,
      },
    },
  ],

  signoffs: [
    {
      id: "mock-signoff-1",
      incidentId: "mock-incident-1",
      role: "REPORTING_STAFF",
      userId: "mock-user-reporter",
      signerName: "James Oduya",
      signedAt: new Date("2026-03-12T11:05:00"),
      createdAt: new Date("2026-03-12T11:05:00"),
    },
    {
      id: "mock-signoff-2",
      incidentId: "mock-incident-1",
      role: "COUNSELOR",
      userId: "mock-user-counselor",
      signerName: "Renata Souza",
      signedAt: new Date("2026-03-12T13:20:00"),
      createdAt: new Date("2026-03-12T13:20:00"),
    },
    {
      id: "mock-signoff-3",
      incidentId: "mock-incident-1",
      role: "LEADERSHIP",
      userId: null,
      signerName: "Principal Okafor",
      signedAt: new Date("2026-03-12T15:00:00"),
      createdAt: new Date("2026-03-12T15:00:00"),
    },
  ],

  parentContacts: [
    {
      id: "mock-parent-contact-1",
      studentId: "mock-student-primary",
      guardianId: "mock-guardian-1",
      counselorId: "mock-user-counselor",
      relatedIncidentId: "mock-incident-1",
      relatedSessionId: null,
      method: "PHONE",
      contactDate: new Date("2026-03-12"),
      reason: "Notify guardian of incident and support plan.",
      summary:
        "Spoke with Amara's mother; she was understanding and will reinforce the plan at home.",
      outcome:
        "Agreed to the daily check-in plan and a follow-up call in one week.",
      followUpRequired: true,
      deletedAt: null,
      deletedBy: null,
      createdAt: new Date("2026-03-12T14:00:00"),
      updatedAt: new Date("2026-03-12T14:00:00"),
      guardian: {
        id: "mock-guardian-1",
        fullName: "Lin Chen",
        relationship: "Mother",
        phone: "555-0114",
        email: "lin.chen@example.com",
        address: null,
        occupation: null,
        deletedAt: null,
        deletedBy: null,
        createdAt: new Date("2024-08-01"),
        updatedAt: new Date("2024-08-01"),
      },
    },
  ],
};
